### ISSUE TITLE
Bug: Textlink and Textlink White hover-states are not the same

### ISSUE THREAD

**Issue by synnaf** [Frojd/Frojd-Jewl#6]
Textlink and Textlink White have different hover-states, they should be the same but inverted. I am not sure what the correct version is, but Textlink White loses border bottom on hover. 

https://github.com/Frojd/Frojd-Jewl/blob/f22b4ee1d7b15e2ba7c0761777ebd8756dcd90d9/component-library/app/components/Button/Button.module.scss#L176

**Comment by saraojelind** [comment]
@synnaf Yes, the design of regular text link has changed, so this should be updated

**Comment by synnaf** [comment]
Fixed in newest push and release.
